[package]
name = "taquin"
version = "0.1.0"
authors = ["Thierry Parmentelat <thierry.parmentelat@inria.fr>"]
edition = "2018"

[[bin]]
name = "taquin"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
